### ISSUE TITLE
Not an issue, I'm new to GitHub and not knowing where to put this.

### ISSUE THREAD

**Issue by BrotherWarren** [Synthlight/Hellpoint-Save-Editor#1]
Thank you for creating this. I wanted to use it for a new character. I wanted to make a reusable new character that has all four omnicube jukebox music. I noticed that this only had A. Do you plan on adding the other three?

**Comment by Synthlight** [comment]
It only has 'A' because it's the only one I knew of. I'd need the IDs of the rest of the things to add.

You're in luck though. Earlier today someone gave me a dump of IDs https://docs.google.com/spreadsheets/d/1REcR_a4HFIyYLHdLWSHPQNPiDIYfQx90Z0CslmEcy1w/edit#gid=74244400
And it looks like that's on the list.

So I'll probably fill this out eventually. Maybe over the weekend if I don't get completely lost in HZD.

**Comment by Synthlight** [comment]
Turns out adding the dump only took 10 min. Fixed in v1.2; enjoy.
